// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznT-829x_L83uqQIOTMOMJR5zJrRrEjw',
    appId: '1:305938863528:web:faa060be1a97ba3cd3b99d',
    messagingSenderId: '305938863528',
    projectId: 'acmp-f9d02',
    authDomain: 'acmp-f9d02.firebaseapp.com',
    storageBucket: 'acmp-f9d02.appspot.com',
    measurementId: 'G-JWYBDKC2Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49HXimOd-09xDNYZqt3C2FvilojhRsZY',
    appId: '1:305938863528:android:63c3db5e8eaf6212d3b99d',
    messagingSenderId: '305938863528',
    projectId: 'acmp-f9d02',
    storageBucket: 'acmp-f9d02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKieM6KMiw62wbJiXuq4wvZ0f8-g-w8fA',
    appId: '1:305938863528:ios:50666299688e2cf9d3b99d',
    messagingSenderId: '305938863528',
    projectId: 'acmp-f9d02',
    storageBucket: 'acmp-f9d02.appspot.com',
    iosBundleId: 'com.example.apmc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKieM6KMiw62wbJiXuq4wvZ0f8-g-w8fA',
    appId: '1:305938863528:ios:50666299688e2cf9d3b99d',
    messagingSenderId: '305938863528',
    projectId: 'acmp-f9d02',
    storageBucket: 'acmp-f9d02.appspot.com',
    iosBundleId: 'com.example.apmc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBznT-829x_L83uqQIOTMOMJR5zJrRrEjw',
    appId: '1:305938863528:web:d51dd3d5485b2665d3b99d',
    messagingSenderId: '305938863528',
    projectId: 'acmp-f9d02',
    authDomain: 'acmp-f9d02.firebaseapp.com',
    storageBucket: 'acmp-f9d02.appspot.com',
    measurementId: 'G-FT79FYBDCB',
  );
}
